### ISSUE TITLE
No Linebreaks are displayed

### ISSUE THREAD

**Issue by michary** [nickbnf/glogg#100]
Hi,

since we updated to Glogg 1.0.3 and the application runs for a while, the log-file is not displayed correctly.

![screenshot from 2016-01-19 08 18 23](https://cloud.githubusercontent.com/assets/867772/12412429/bc78dab4-be86-11e5-8bd3-a8a7833f84ee.png)

**Comment by nickbnf** [comment]
Is it still happening on recent versions? A number of bugs have been fixed. If it does, we should try to investigate.

**Comment by nickbnf** [comment]
Closed as not reproducible.
