### ISSUE TITLE
Multiple Instances at Once or Split-Screen Tab View

### ISSUE THREAD

**Issue by GarethPW** [nickbnf/glogg#105]
These features would be great since I'm currently unable to use glogg to monitor multiple files effectively.

**Comment by variar** [comment]
There is comand-line switch --multi that allows multiple instances to start

**Comment by variar** [comment]
It's worth mentioning that [Klogg](https://github.com/variar/klogg) has a multi-window mode. In this mode there is only one instance of klogg running, but you can open multiple windows to view different files.
