### ISSUE TITLE
Support for multibyte encodings

### ISSUE THREAD

**Issue by variar** [nickbnf/glogg#110]
Support for utf-8 is great. However, current implementation can't be easily extended to support multibyte encodings like utf-16/utf-32.  Adding encoding for display purposes is trivial. The problem is that index of line positions is created using manual detection of 'newline' characters assuming it is encoded using 8 bits. In utf-16 each character is encoded using 16-bits. Moreover utf-16 can use either 'little endian' or 'big endian' making handling of '\n' character even more complex.

Right now I can't come up with a solution which will be on one hand easy to merge into current implementation and on the other hand will not feel like a kludge. If you have an idea how to do it the right way I'll be happy to do the coding.

**Comment by variar** [comment]
I've done some experiments. QTextStream::readLineInto(nullptr) can be used to do all multibyte handling without copying data to actual QString object. Should be fast enough for indexing line positions. However, LogData uses QFile::readLine() to get actual text lines and that method is unaware of character width. It is possible to use QTextStreem here also.

**Comment by petertirrell** [comment]
Would this explain weirdness in viewing files that I think are encoded in UTF16? I see two funny characters at the very beginning of a sample file, and each line of the file is truncated in the view mid-way across.  I can scroll to the right and that makes the rest of the text appear in the viewport.  And if I highlight/select text, it "pushes" the text on the row to the right as I drag across, and the cursor has to be dragged multiple spaces to actually select a single character.

**Comment by variar** [comment]
Yes, that's the issue. I've come up with a solution. One can try to encode "\n" character to check resulting number of bytes as well as bytes order. Using this information it is possible to build line index almost without modification. I'd be happy to share this code, however right now it might be difficult because of accumulation of other changes.

If you are brave enough check my fork (klogg). I'm using it heavily in day to day work.

**Comment by nickbnf** [comment]
Do utf-16 (I understand Windows generate some) files typically include a BOM as a first character?

**Comment by variar** [comment]
Usually BOM is present. However, one migth be opening partial log file where BOM is not present. One real world example is getting last lines of log from in-memory buffer stored in crash-dump.

**Comment by variar** [comment]
This 'line feed' encoding trick is actually needed not to detect encoding but to avoid having big switch-case for mapping specific encoding to its character width which is essential for building correct line index. Encoding is either detected by Qt (for UTF variants) or selected manually.

Check https://github.com/variar/klogg/commit/0610721139e53bd0707f42a0d86b3cb4b25d43e8 IndexOperation::doIndex implementation.  If you find this idea usefull I'll prepare pull-request for current glog master with these changes.

**Comment by nickbnf** [comment]
Introduced utf-16 in 4a4a124ee3a37b84cecba5baf80e1ecc23769c38. Does anybody use UTF-32?
