### ISSUE TITLE
Fedora - root privileges

### ISSUE THREAD

**Issue by mlopezcoria** [nickbnf/glogg#113]
Hey,

I had to make a file in order to execute glogg with root privileges in **fedora 23 cinnamon spin** and I wanted to share it, because it may be helpful and you can include it.

The hole explanation is here in fedora forum http://forums.fedoraforum.org/showthread.php?t=308300

Thank you!

**Comment by nickbnf** [comment]
Thanks, but as you explained in the thread, it is an issue with packaging for Fedora, and as I understand it not specific to glogg.
