### ISSUE TITLE
Scrolling trough 32 GB file

### ISSUE THREAD

**Issue by guillaume-chevalier** [nickbnf/glogg#115]
I simply scrolled trough nearly 300 lines in a 32 GB file under Ubuntu 14 LTS. I Installed glogg from apt-get, fresh install. 

gui@gui-Satellite-P50-A:/media/gui/Data/datasets/reddit_comments$ glogg RC_2015-01
- 14:56:34.792 WARNING savedsearches.cpp:124: Trying to import legacy (<=0.8.2) saved searches...
- 14:56:34.792 WARNING savedsearches.cpp:128: ...imported searches: 0 elements
- 14:56:34.792 WARNING filterset.cpp:208: Trying to import legacy (<=0.8.2) filters...
- 14:56:34.792 WARNING filterset.cpp:212: ...imported filterset: 0 elements
  QIODevice::read: maxSize argument exceeds QByteArray size limit
  Killed

**Comment by nickbnf** [comment]
Which version are you using? Versions prior to 1.0.3 had significant problems when dealing with (very) big files, this should now work fine on newer versions.

**Comment by guillaume-chevalier** [comment]
It is an old version:
`$ glogg --version`
`glogg 0.9.2-1`
It may be interesting to update the version on `apt-get` then

**Comment by egorlitvinenko** [comment]
It's the last version in Ubuntu repository. It will be wonderfull, if you upgrade it.

**Comment by variar** [comment]
It seems that there is package for version 1.1.0 here https://www.ubuntuupdates.org/package/core/yakkety/universe/base/glogg

**Comment by egorlitvinenko** [comment]
Unforunately it's not compatible:
http://pix.toile-libre.org/upload/original/1491735969.png

The error is "Unresolvable dependency".

**Comment by variar** [comment]
@egorlitvinenko which version of Ubuntu are you using? I've posted a link to glogg package for 16.10.  According to http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=glogg&searchon=names package for version 1.1.0 exists since 16.04. Unfortunately there is no package for older versions.

**Comment by egorlitvinenko** [comment]
I use 14.04

**Comment by nickbnf** [comment]
I don't know of anyone maintaining new versions of glogg for older ubuntu version (ppa or backport) although that would be very useful if someone want to volunteer!
@egorlitvinenko you can build the latest from source though which is quite simple (see README).

**Comment by egorlitvinenko** [comment]
@nickbnf Ubuntu 14.04 isn't old it is LTS and will be actual to 2019 year :)
I tried to build, but build fails with README instruction. I think it simpler to use docker with Ubuntu 16.04 and already built version.

**Comment by Kentoseth** [comment]
@egorlitvinenko do you still have the output of the failed-build on 14.04 ?
