### ISSUE TITLE
Last line in search results is not visible

### ISSUE THREAD

**Issue by MartinGernhard** [nickbnf/glogg#116]
glogg-v1.1.1-1-x86_64-setup.exe

The last line of search results is not shown and can not be reached with the scroll bar. If I use the mouse wheel to scroll down "beyond the end" the last line becomes partially visible for a short amount of time but then the view scrolls back immediately. If I use the mouse wheel to scroll down *very* fast the last line and the yellow/grey end marker become visible.

**Comment by Mark-Hobba** [comment]
I have the same problem and it prevents me from using glogg.  Such a pity since it looks like such a great tool overall, but I need to be able to see that last line of my log files.

glogg 1.1.1-x86_64
Windows 7, 64bit, fully up to date with updates.

**Comment by rgwood1234567890** [comment]
Thanks for the great tool!

I have also noticed this on 1.1.1 64 bit windows. Files are ACSII and a simple "tail <filename>" in bash shows the correct last lines.

Maybe this tool assumes a "\r\n" at the end of a file as opposed to just the last byte of the last line?

**Comment by variar** [comment]
This is the result of scrolling algorithm. Scrolling is done not per pixel but per line. And scrolling position is adjusted so the **first** line in search results is fully visible. This obviously makes last line cut off sometimes.

**Comment by rgwood1234567890** [comment]
In my case this was not in the search area; it was in the main text view panel.

**Comment by rgwood1234567890** [comment]
For example, the last line I see in glogg is "16874593,521828,0"

$ tail clicks_train.csv
16874591,397506,0
16874591,483448,0
16874592,82851,0
16874592,153244,1
16874592,167294,0
16874592,186600,0
16874593,151498,1
16874593,282350,0
16874593,521828,0
16874593,522693,0

$ tail clicks_train.csv | hexdump.exe
0000000 3631 3738 3534 3139 332c 3739 3035 2c36
0000010 0a30 3631 3738 3534 3139 342c 3338 3434
0000020 2c38 0a30 3631 3738 3534 3239 382c 3832
0000030 3135 302c 310a 3836 3437 3935 2c32 3531
0000040 3233 3434 312c 310a 3836 3437 3935 2c32
0000050 3631 3237 3439 302c 310a 3836 3437 3935
0000060 2c32 3831 3636 3030 302c 310a 3836 3437
0000070 3935 2c33 3531 3431 3839 312c 310a 3836
0000080 3437 3935 2c33 3832 3332 3035 302c 310a
0000090 3836 3437 3935 2c33 3235 3831 3832 302c
00000a0 310a 3836 3437 3935 2c33 3235 3632 3339
00000b0 302c 000a
00000b3

$

**Comment by rgwood1234567890** [comment]
The "-C" makes more sense:

```
$ tail clicks_train.csv | hexdump.exe -C
00000000  31 36 38 37 34 35 39 31  2c 33 39 37 35 30 36 2c  |16874591,397506,|
00000010  30 0a 31 36 38 37 34 35  39 31 2c 34 38 33 34 34  |0.16874591,48344|
00000020  38 2c 30 0a 31 36 38 37  34 35 39 32 2c 38 32 38  |8,0.16874592,828|
00000030  35 31 2c 30 0a 31 36 38  37 34 35 39 32 2c 31 35  |51,0.16874592,15|
00000040  33 32 34 34 2c 31 0a 31  36 38 37 34 35 39 32 2c  |3244,1.16874592,|
00000050  31 36 37 32 39 34 2c 30  0a 31 36 38 37 34 35 39  |167294,0.1687459|
00000060  32 2c 31 38 36 36 30 30  2c 30 0a 31 36 38 37 34  |2,186600,0.16874|
00000070  35 39 33 2c 31 35 31 34  39 38 2c 31 0a 31 36 38  |593,151498,1.168|
00000080  37 34 35 39 33 2c 32 38  32 33 35 30 2c 30 0a 31  |74593,282350,0.1|
00000090  36 38 37 34 35 39 33 2c  35 32 31 38 32 38 2c 30  |6874593,521828,0|
000000a0  0a 31 36 38 37 34 35 39  33 2c 35 32 32 36 39 33  |.16874593,522693|
000000b0  2c 30 0a                                          |,0.|
000000b3

```

**Comment by Mark-Hobba** [comment]
@variar, the last line not being visible/scrollable happens every time I open a log file with glogg on windows, ie it is not connected to using the search function at all.  If I just open a log file, drag the scrollbar thumb down to the bottom without doing anything else, the last line is cut off or has only a couple of pixels of the top of the line visible.
I imagine a quick hack fix would be to allow the scroll to move one lineheight further than it does now.  On machines/operating systems without this bug, it will just show them a blank line.

**Comment by nickbnf** [comment]
@Mark-Hobba this is happening across all OSes in the latest version, as @variar said this is because of the way lines are drawn and scrolled. An easy workaround is to resize the window slightly to make the last line visible, that will work every time but obviously is not ideal. I am working on a fix now.

**Comment by Mark-Hobba** [comment]
Thank you so much for fixing this!  I tried it in 1.1.2 just now and it is very much appreciated.
