### ISSUE TITLE
Hangs up in case try scroll result list 

### ISSUE THREAD

**Issue by OleksandrMelnyk** [nickbnf/glogg#117]
Problem:
1 - window for result not cleaned after new search without result 
2 - glogg hangs up in case try scroll result list 

glogg 1.1.0-1 ubuntu 16.04 

Sequence to reproduce :
1- Open file ~1-2Mb
2 - Search pattern with a lot of results 
3 - Try search other pattern without result 
4 - In window with result try scroll use mouse wheel without select window 
Result : 
- window for result not cleaned after new search without result 
- glogg hangs up

In console:

 glogg
QObject::connect: Cannot connect (null)::loadFile( const QString& ) to MainWindow::loadFileNonInteractive( const QString& )
QObject::connect: No such signal AbstractLogView::followDisabled()
- 17:13:05.991 WARNING src/data/logdataworkerthread.cpp:298: Cannot open file /tmp/.fr-uSv4Be/cmd_E236b1176HdevLog1.txt
- 17:13:05.994 WARNING src/watchtower.h:179: WatchTower::addFile driver failed to add dir
  QObject::connect: No such signal AbstractLogView::followDisabled()
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 4294967295
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 0
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 1
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 2
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 3
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 4
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 5
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 6
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 7
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 8
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 9
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 10
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 11
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 12
- 17:13:46.819 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 13
  ...
  
  17:13:52.933 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 397794
- 17:13:52.933 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 397795
- 17:13:52.933 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFilteredData: 397796
- 17:13:52.933 ERROR src/data/logfiltereddata.cpp:283: Index too big in LogFiltere^C

**Comment by nickbnf** [comment]
This is an issue on 1.1.0 and has been fixed by 8ea5bc4cf192a6c6287db6ac5c56058f9d88fd6f
