### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by KMV16** [nickbnf/glogg#119]
Hi! Your program is great for review big log files!

Could you please add windows-1251 encoding

Now if i open file  with Cyrillic charaters i see something like this 
(-4585) Äëÿ ýòîé îïåðàöèè íåîáõîäèìî ñîåäèíåíèå ñ ñåðâåðîì. Óñòàíîâèòå ñîåäèíåíèå è ïîïðîáóéòå åùå ðàç.

**Comment by e-orz** [comment]
variar build (look in the forks) has CP1251

**Comment by nickbnf** [comment]
Added in f25e35f2304d4fe5dd984cd59b86e6255c85ffe4
