### ISSUE TITLE
Fonts are jagged

### ISSUE THREAD

**Issue by rnyberg** [nickbnf/glogg#120]
It seems like there is no anti-aliasing, so most fonts look really bad. Would really like if hinting/AA was included, thanks! :)

**Comment by nickbnf** [comment]
It is! What platform are you running?

**Comment by variar** [comment]
Some screenshot could also be helpful. Qt should use nice fonts by default.

**Comment by nickbnf** [comment]
Please re-open if it is still a problem, most people are happy with the fonts.
