### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by bgammill** [nickbnf/glogg#121]
Good day everyone. Whenever I open the application and try to load a file, I get the error attached. After closing the error dialog, I can successfully open a file. Any ideas as to why this is occurring? Thanks!

![entrypoint](https://cloud.githubusercontent.com/assets/1501774/17191674/35146d1e-5408-11e6-9b05-247dbae014d0.png)

**Comment by nickbnf** [comment]
Which version/platform? Can you still see this on the latest version?

**Comment by nickbnf** [comment]
Closed as non reproducible.
