### ISSUE TITLE
[Feature Request] Save/Restore Window size and location

### ISSUE THREAD

**Issue by darickard** [nickbnf/glogg#130]
It would be great if the saving and restoring of the Glogg window size and location could be added so that, when launched, the window size and position is the same as when Glogg was last running. This is a pretty standard feature of most Windows apps (not sure about Mac & Linux).

Thanks for a great app!

**Comment by variar** [comment]
Hi!
Which version are you using? Is checkbox "Load last session" in Tools->Options checked? Quickly looked through source code and in seems that requested feature is there, but it is enabled only if glog is loading last session at startup.

**Comment by darickard** [comment]
Thank you for the response.

I'm using v1.1.2-x86_64 on Windows7. I've tried it with and without "Load last session" checked, but it doesn't work either way.

Even if it did, I would suggest decoupling the window size and location restoration from that feature since the user may want the window size and location to be the same on each startup but not want to open the last opened file. For me, I don't ever want it to reopen the last file, but I do always want it to open at the same size and location.
