### ISSUE TITLE
Open multiple files from command line

### ISSUE THREAD

**Issue by kwill** [nickbnf/glogg#131]
I am logging multiple applications. Some applications generate multiple logfiles, not necessarily in the same folder. I'd like to launch a separate instance of glogg for each application, with all logfiles for that application in that instance.

A simple solution would be to make a Windows shortcut calling `glogg.exe C:\path\file1.log C:\path2\file2.log` -- but this didn't work, and I couldn't find docs on command line options. Is it possible to open multiple files at once from the command line?

**Comment by Sadi58** [comment]
If you are not particulary interested in opening new tabs, you should be able to do that like this:
```
glogg.exe --multi C:\path1\file1.log
glogg.exe --multi C:\path2\file2.log
```
It does work under Linux (Ubuntu).

```
Usage: glogg [options] [file]:
  -h [ --help ]          print out program usage (this message)
  -v [ --version ]       print glogg's version information
  -m [ --multi ]         allow multiple instance of glogg to run simultaneously
                         (use together with -s)
  -s [ --load-session ]  load the previous session (default when no file is 
                         passed)
  -n [ --new-session ]   do not load the previous session (default when a file 
                         is passed)
  -d [ --debug ]         output more debug (include multiple times for more 
                         verbosity e.g. -dddd)
```

**Comment by variar** [comment]
If you want to open several files in one instance of glogg you can create a cmd-scipt (.bat) with something like this:

```cmd
SETLOCAL
SET glogg="<Full_Path_to_glogg.exe_here>"
call %glogg% C:\path1\file1.log
call %glogg% C:\path2\file2.log
```

From here it can be expanded to accept any number of log files using for-loop for script arguments.

p.s.
not tested above code, might need some more hacking :)

**Comment by Sadi58** [comment]
@variar any chance of doing that in bash script (.sh) as well?
Something like `glogg 'file1.log' & glogg 'file2.log'` results in multiple instances.

**Comment by variar** [comment]
@Sadi58 this one works for me 
```sh
#!/bin/sh

GLOGG=./glogg

for filename in "$@"
do
    echo "$filename"
    $GLOGG $filename &
done
```

When first file is open glogg starts listening for incoming connections through some platform-specific IPC (dbus on linux, something similar on other platforms). Every following instance passes a filename to the first one and silently dies unless -m flag is specified on command line.

**Comment by Sadi58** [comment]
@variar  thank you very much.
I guess the first line sets the path to glogg binary/executable, which is `/usr/bin/glogg` in my case.
So if I name this script as Glogg and place it under `~/.bin`, shall I use it like this: `~/.bin/Glogg "file1.log" "file2.log"` ?
As this also results in multiple instances, I guess I'm missing something.
Sorry, a beginner in bash scripts here ;-)

**Comment by variar** [comment]
Calling looks fine for me. You might need to increase sleep delay (try something like 1 for 1 second and decrease it gradually) to allow first instance to set up d-bus properly. 

Also what version of glogg are you using? And while glogg is launched are you able to find its dbus endpoint?  This long command 
```
dbus-send --session --dest=org.freedesktop.DBus   --type=method_call  --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep glogg
```
should print
```
string "org.bonnefon.glogg"
```

**Comment by Sadi58** [comment]
I'm using version 1.1.0 in Ubuntu repositories, and that command returns nothing, I just get a new empty line in terminal window.

**Comment by variar** [comment]
Does launching glogg with -dd switch produce something about D-bus? On my machine first launch prints
```
$ glogg -dd
- 00:05:04.871 INFO src/dbusexternalcom.cpp:63: Cannot find external D-Bus correspondant, we are the only glogg out there.
...
```
Launching second instance prints
```
$ glogg -dd
- 00:07:30.100 DEBUG src/main.cpp:201: externalInstance = 0x1c76e10
- 00:07:30.101 INFO src/main.cpp:204: Found another glogg (version = 10000)
```

glogg can be built without d-bus support, but I can't find what build options were used for ubuntu package

**Comment by Sadi58** [comment]
Hmm, there's probably a problem here, as I get 263 lines of -mostly- DEBUG warnings starting with these:
```
- 00:11:19.230 DEBUG src/main.cpp:194: externalInstance = 0
- 00:11:19.254 DEBUG src/configuration.cpp:48: Default font is DejaVu Sans Mono
- 00:11:19.255 DEBUG src/configuration.cpp:69: Configuration::retrieveFromStorage
- 00:11:19.255 DEBUG src/savedsearches.cpp:103: SavedSearches::retrieveFromStorage
- 00:11:19.295 DEBUG src/recentfiles.cpp:81: RecentFiles::retrieveFromStorage
- 00:11:19.296 DEBUG src/filterset.cpp:187: FilterSet::retrieveFromStorage
QObject::connect: Cannot connect (null)::loadFile( const QString& ) to MainWindow::loadFileNonInteractive( const QString& )
- 00:11:19.296 DEBUG src/main.cpp:247: MainWindow created.
- 00:11:19.309 DEBUG src/sessioninfo.cpp:30: SessionInfo::retrieveFromStorage
- 00:11:19.309 DEBUG src/sessioninfo.cpp:40: SessionInfo: 1 files.
- 00:11:19.309 DEBUG src/sessioninfo.cpp:30: SessionInfo::retrieveFromStorage
- 00:11:19.309 DEBUG src/sessioninfo.cpp:40: SessionInfo: 1 files.
- 00:11:19.309 DEBUG src/session.cpp:124: Session returned 1
- 00:11:19.309 DEBUG src/session.cpp:129: Create view for /var/log/kern.log
QObject::connect: No such signal AbstractLogView::followDisabled()
- 00:11:19.324 DEBUG src/crawlerwidget.cpp:217: CrawlerWidget::doSetViewContext: S421:147:IC1:AR0
```

**Comment by variar** [comment]
It looks like that ubuntu package is built without dbus support. Logs from src/dbusexternalcom.cpp have been there since 2014, so they should be in glogg debug output if dbus is enabled during compilation.

**Comment by Sadi58** [comment]
OK, thanks a lot for the effort anyway.
I can do with the start with last session until that feature arrives.

**Comment by nickbnf** [comment]
Closed as glogg now supports several files on the command line. I'll check whether ubuntu builds with dbus, it should.

**Comment by Sadi58** [comment]
Great news! Now I have to wait until it arrives in Ubuntu repositories (which still uses version 1.1.0-1build3) or do a manual build...
