### ISSUE TITLE
tab switching using Alt+<num> keys

### ISSUE THREAD

**Issue by Avinash-Bhat** [nickbnf/glogg#139]
Using the Alt+<Num> keys to switch between the tabs will be very helpful to the mostly-uses-only-keyboard users. 

I have selected the Alt+<Num> keys as it is an accepted shortcut for fast switching between tabs in other applications like chrome(ium), sublime text, ...

**Comment by nickbnf** [comment]
Chrome uses Ctrl/Cmd 1-9 and Cmd/Opt >/< to switch tabs, and so does glogg! But testing this I realised there was a bug on macOS preventing this from working, now fixed.
