### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by glogg-user** [nickbnf/glogg#144]
hi, trying to compile on an PCLinuxOS getting following error

uname -> Linux 4.6.3-pclos1 #1 SMP Fri Jun 24 15:24:36 CDT 2016 x86_64 x86_64 x86_64 GNU/Linux

[output from qmake]

Project MESSAGE: Building using system dynamic Boost libraries
sh: line 0: type: markdown: not found
Project MESSAGE: markdown not found, HTML doc will not be generated
g++ (GCC) 4.9.2
Project MESSAGE: g++ version 4.7 or newer, supports C++11
Project MESSAGE: Support for D-BUS will be included
Project MESSAGE: Version checker will NOT be included
Project MESSAGE: File watching using inotify

[/output from qmake]

========================

[output from make]

g++ -c -g -Wextra -std=c++11 -DGLOGG_VERSION=\"`cat .tarball-version`\" -DGLOGG_SUPPORTS_DBUS -DGLOGG_SUPPORTS_INOTIFY -O2 -Wall -W -D_REENTRANT -DFILELOG_MAX_LEVEL="logDEBUG" -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtDBus -I/usr/include -Isrc -I.moc/release-shared -I.ui/release-shared -o .obj/release-shared/main.o src/main.cpp
src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:242:23: error: ‘AA_UseHighDpiPixmaps’ is not a member of ‘Qt’
     app.setAttribute( Qt::AA_UseHighDpiPixmaps );
                       ^
Makefile:585: recipe for target '.obj/release-shared/main.o' failed
make: *** [.obj/release-shared/main.o] Error 1

[/output from make]

thx for any ideas

fritz
(-:fs)

**Comment by nickbnf** [comment]
Could you please check which version of Qt your distribution have? (`qmake  --version`)

A quick fix would be to comment out the faulty line in main.cpp, but you might encounter problems with supporting High DPI screens.

**Comment by glogg-user** [comment]
here my version -

qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib64

thx

fritz
(-:fs)

**Comment by nickbnf** [comment]
New versions of glogg require Qt 5 to be built. Depending on your distribution you might need qmake-qt5, qmake5 or something similar.
