### ISSUE TITLE
Open a file from command line (with relative path)

### ISSUE THREAD

**Issue by senhalil** [nickbnf/glogg#145]
In macos terminal, to open a file with glogg, one needs to give the full path of the file which is really inconvenient sometimes.  I don't know, maybe I am doing something wrong. I use the following code `open -a glogg --args /full/path/to/the/file`. 

For example, one can open the same file sublime text as follows `open -a "Sublime Text" file`. Note that the command uses a relative path and the `--args` is missing because `open` passes the arguments after the application name as filenames by default -- i.e.,`open [Options] [-a <application>] [filenames] [--args arguments]`.

I am guessing there is a missing `pwd` in the file opener of glogg and an incompatibility with the `open` command of macOs.

**Comment by vbu** [comment]
+1. I use glogg heavily but this limitation doesn't allow to set association for 'Open With.." to all my log files (so that when I double click a file with '.log' extenstion, for example, it gets opened in glogg automatically). I have to manually drag them into already opened glogg window.

**Comment by gschneider-r7** [comment]
Seems like qt events need to be used: https://stackoverflow.com/questions/26849866/unable-to-open-file-with-qt-app-on-mac basically Mac OS isn't sending arguments like you would expect on Windows or Linux.

I found that running from the command line like `/Applications/glogg.app/Contents/MacOS/glogg myfile.log` works, but doesn't return your terminal until you close the window.

**Comment by gschneider-r7** [comment]
I see this is closed with new code on master branch, is there an ETA for a new release that includes the changes? 😃
