### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by svatauli** [nickbnf/glogg#149]
Hi,
sometimes glogg create this https://ibb.co/cMyL5a exception.

version: 1.1.3 

SU

**Comment by pavelvasev** [comment]
In my cases this bug occurs when monitored file recreated by another program. 
E.g. the file opened by that another program with "write" flag.

**Comment by svatauli** [comment]
Probably yes, I use glogg to watch log in running application. So when application creates new log file by log settings, glogg should be hide this exception.

**Comment by nickbnf** [comment]
This is bad. I'll try to debug it but I need as much information as possible or, ideally, a reproducible scenario. Could you tell me:
- What application is generating the changing log.
- How often is the fault appearing.
- When is it appearing (after a long time, immediately, it depends...).
- Is it new in 1.1.3 or had you noticed the problem on earlier version too.
- What OS version (I assume Windows from the screenshot) are you using.
Thanks!

**Comment by pavelvasev** [comment]
* What application is generating the changing log.
Custom application. When it starts it opens log file with "w" flag and immediately closes it. Then, every time a log record appears, the application reopens log file with "a" flag, writes data, and closes it. 

* How often is the fault appearing.
Everytime the custom application starts. 

* When is it appearing 
Right after custom application starts.

* Is it new in 1.1.3 or had you noticed the problem on earlier version too.
There was no such problem in glogg version 1.0.2

* What OS version
Windows 7 sp1

**Comment by pavelvasev** [comment]
Program to reproduce the bug: `a.cmd`
```
echo 123 >a.log
echo xxxxxxxxxxxxxxxxx >>a.log
echo xxxxxxxxxxxxxxxxx >>a.log
echo xxxxxxxxxxxxxxxxx >>a.log
echo xxxxxxxxxxxxxxxxx >>a.log
```
How to use:
1. Run the program.
2. Open the log file in Glogg.
3. Run the program again, and see runtime assertion window.

**Comment by nickbnf** [comment]
Thanks @pavelvasev, I can't reproduce the problem on my virtual machine but I suspect a race condition when the file is re-created. Could you please produce a log by running glogg this way: glogg -l -dddddd
It will produce a log in the same directory (glogg_xxxx.log).
Thanks a lot

**Comment by pavelvasev** [comment]
Hi @nickbnf ! Thank you for your help! Here are 2 log files:
* [glogg_11200.log.txt](https://github.com/nickbnf/glogg/files/924089/glogg_11200.log.txt)
* [glogg_4612.log.txt](https://github.com/nickbnf/glogg/files/924088/glogg_4612.log.txt)

**Comment by nickbnf** [comment]
Thanks a lot @pavelvasev for your help, could you verify 1.1.4 that I have just uploaded fixes the problem for you? I'll write the announcement once verified.

**Comment by pavelvasev** [comment]
Hi @nickbnf ! I confirm that 1.1.4 is working properly. Thank you very much for your attention and help!!!......
