### ISSUE TITLE
Messed printing when following deleted and recreated logs

### ISSUE THREAD

**Issue by Lightjohn** [nickbnf/glogg#151]
Hi,

I'm working and debugging an application and from time to time I delete the logs and the application will recreate them seconds later.
But the problem is that glogg is missing the new lines characters and so the printing is bad.

I'm using the latest version from the git.
I know it's not an usual way to work and just wanted to let you know that.

**Comment by bristolweb** [comment]
I have a similar problem. I upgraded recently to 1.1.3 from 0.9 on linux Mint 17.3 (Rosa). Reason for upgrading: I needed more than the 5 logs easily available from 0.9. I really like the new 1.1.3 tabs for selecting each log! :)

Version 1.1.3 seems fine except that every time one of the logs is rotated (ie most mornings depending on the log) I have to drop glogg and reload it. Not a major problem since unlike syslog viewer the log names and filter colours are retained and all I have to do is hit Follow for each log. Still annoying, though. Reload has no effect on this.

Primary logs used in this situation are mail (postfix), dovecot, spamd, clamav and ubound. Various apache logs are also viewed depending on current needs. Mail log is usually ok but dovecot always displays with no regard for newlines.

**Comment by nickbnf** [comment]
Could you check if the problem is still happening with 1.1.4? A bug was fixed that might be the root cause for what you are seeing as well.

**Comment by bristolweb** [comment]
Not sure how to download/install 1.1.4 - apt-get install just says "latest version installed". Could you give some idea, please? Linux Mint 17.3.

**Comment by Lightjohn** [comment]
Compiling using latest git I get this version "Built 2017-05-19 from
624d1a5".
Nothing changed and it seems even a little bit worse: it was only filling
with blank line (happen twice).

So it seems for now that I will have to restart glogg at each logs reset.
But if I let it open long enough, it seems that the problem solve itself.

Thanks.

**Comment by Lightjohn** [comment]
Compiling using latest git I get this version "Built 2017-05-19 from 624d1a5".
Nothing changed and it seems even a little bit worse: it was only filling with blank line (happen twice).

So it seems for now that I will have to restart glogg at each logs reset.
But if I let it open long enough, it seems that the problem solve itself.

**Comment by nickbnf** [comment]
OK, so we have a real problem here, the fact reloading is not doing anything is especially bizarre. Do you have a scenario where you can reproduce the problem 100%? I'll give it a try.

**Comment by Lightjohn** [comment]
Hi sorry for the late comeback, I'm still getting the issue so just went back and saw your message.
At least with time I know exactly what cause the issue in my case.
My application is rotating the log every hour and every time it happen while I'm watching, the output will be all messed up.
So I think just: 

move current log and and wait for the application to recreate it is enough in my case.

It's still happening for me and I compile directly from git from time to time (just done that before that message).
Do you want a script that could reproduce it?

**Comment by gin-ahirsch** [comment]
Can you try PR #222? It changes things when re-opening files some.

**Comment by Lightjohn** [comment]
I just tried and it's working :)
It seems I will just have to wait for your changes to be merged.

Thank you

**Comment by Lightjohn** [comment]
In my case it's just log4j auto rotate option, so the file would be very briefly an empty file, then a lot of logs will be appended.

**Comment by crazycliffy** [comment]
Anyone experiencing any issue with this still?  I compiled from the latest version 1.1.4 for linux (redhat/centos) target.  When the file gets rolled over (e.g. "mv file.log file.log.1; cp file.log.1 file.log"), I see garbled, messed up text displayed in glogg.   Using the Reload (Ctrl-R) feature does not fix the issue. As a workaround, I have to close the file, and just reopen it.

**Comment by Lightjohn** [comment]
I still have this issue.
Same I just close and re open the app all the time.
And because I use glogg as debug tool I close reopen it quite a lot

**Comment by variar** [comment]
@Lightjohn is this issue present in glogg built from latest master? I've chery-picked fix into my fork, but if the problem is still present in glogg master, then I'll have to find some other fix.

**Comment by Lightjohn** [comment]
@variar Latest build from master seems OK I played with it a little bit by moving logs with a script.

So the fix is not in buntu repo but that's another story! Fix is here and working. Thank you
