### ISSUE TITLE
Error: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by jlanzarotta** [nickbnf/glogg#154]
Hello,

If for example, I have a log file open in glogg and the log file rolls over at midnight, I get an exception saying that my application cannot access the log file because it is being used by another process...

Any ideas?  Thanks.

**Comment by jlanzarotta** [comment]
Anyone else seeing this sort of thing happen to them?

**Comment by variar** [comment]
Hi, see #109. File is kept open by glogg for performance reasons

**Comment by nickbnf** [comment]
Yep, closed as a duplicate of #109.
