### ISSUE TITLE
More keyboard shortcuts

### ISSUE THREAD

**Issue by sergei-dyshel** [nickbnf/glogg#156]
Some shortcuts that I'm missing:
 - Moving between tab pages.
- Moving between normal/filter sections.
- Adjust splitter.
- Clean filter view (i.e. leave only pinned lines).

**Comment by nickbnf** [comment]
- Moving between tab pages: Ctrl+Alt+Left/Right arrows (or Cmd+Option) or Ctrl-Tab/Ctrl-Shift-Tab, like Firefox.
- Moving between normal/filter sections: Tab/Shift-Tab (go through search bar)

Is it ok?

For the two others, I will add shortcuts.

**Comment by sergei-dyshel** [comment]
*ctrl-tab* indeed works, somehow missed it :smile:
Moving between normal/filter secions with *tab* is possible but not intuitive - when pressing *tab* in normal section it moves to the following interface elements: filter text, search button, marks/matches dropdown, "ignore case" checkbox, "auto-refresh" checkbox and only then to filter section. It's much easier to just press *ctrl-tab* twice to go in backward direction. But it would be nice to switch with single keypress.

**Comment by sergei-dyshel** [comment]
And last, but not least: changing font size with *ctrl-scroll*.
