### ISSUE TITLE
Use QRegularExpression as regular expression engine

### ISSUE THREAD

**Issue by sergei-dyshel** [nickbnf/glogg#159]
During browsing the code I've found that `glogg` still uses `QRegExp` class, while Qt5 introduces new `QRegularExpression` class which leverages PCRE (with JIT capabilities).
AFAIU new class must have better performance.

**Comment by forty8bits** [comment]
This would also enable greedy quantifiers such as `*?` and `+?`, which is sorely missing currently.

**Comment by nickbnf** [comment]
Done in 7cbb2ca4497ec8f4a20fe2586dec49657d3308cb
