### ISSUE TITLE
Later glogg version past 1.1.0 from apt repositories

### ISSUE THREAD

**Issue by nkolban** [nickbnf/glogg#162]
I have installed the latest Glogg on Ubuntu by executing:

```
$ sudo apt-get install glogg
```

The version reported is 1.1.0.

I am finding that when the underlying file being watched is removed and replaced with a new one, glogg no longer follows correctly.   My next plan was to file an issue but then I noticed that 1.1.0 is < 1.1.4 which appears to be the latest.  My hope was to obtain and install a new "apt" installable of the latest version and test to see if the problem has already been resolved at the latest builds.  If it hasn't then I would file an issue.

But before then, I'd like to get my hands on a pre-compiled installable for Ubuntu.

**Comment by nickbnf** [comment]
Closed as not a glogg bug.
