### ISSUE TITLE
Can't search on UNICODE encoded files

### ISSUE THREAD

**Issue by omellet** [nickbnf/glogg#166]
I can open a UCS-2 encoded file, but search doesn't show any results. If I save the same file (in another editor) as UTF-8 or ASCII and reopen it in glogg, search works once again.

**Comment by variar** [comment]
Which version are you using? It seems to me that UTF-16 support has been added only in 2f6fa4628fc30ec8c0de04db338125ee1e7f7ae8, and no build has been released yet.

**Comment by omellet** [comment]
This is on v1.1.4-x86_64. If it's forthcoming then I'll just close the issue, thanks.
