### ISSUE TITLE
Continuous Integration using travis

### ISSUE THREAD

**Issue by nickbnf** [nickbnf/glogg#169]
@variar how do you suggest I do that? Shall I try and cherrypick all your commits to do with CI or should I copy and add your travis config?

**Comment by variar** [comment]
It is pretty straightforward process. Firstly, use account from github to register with http://travis-ci.org (linux + mac builds) and http://appveyor.com (win build). Then enable ci for glogg repository with all settings set to default. And finally, push configuration files (see PR  #170). Travis and Appveyor should notice new commit, pick up configuration and start building.

**Comment by nickbnf** [comment]
Thanks, that seems to work!
