### ISSUE TITLE
feature request: log format specifications

### ISSUE THREAD

**Issue by selfagency** [nickbnf/glogg#171]
i use [winston](https://github.com/winstonjs/winston) for logging in node.js, which outputs logs in json format. this has worked great in [lnav](https://github.com/tstack/lnav), for which i was able to add [a simple format file](http://codegist.net/snippet/json/winston_logjson_p2kmgcl_json) to properly interpret the output. it would be great if there was a way to create such formats for different logger types in glogg or maybe some way in the gui to manually map JSON output fields to glogg's existing types. in the short term, it would be great if there was at the very least a way to pretty print JSON output in glogg. presently the output in glogg comes out like this:

```
{"level":"info","message":"\u0007 Server listening on port 3030","timestamp":"2017-07-25T19:19:55.827Z"}
{"level":"info","message":"\u0007 Server listening on port 3030","timestamp":"2017-07-25T21:24:59.226Z"}
```

it's readable and all, but it's not really the best way to view such logs.

**Comment by selfagency** [comment]
well, the way lnav would represent the above is:

`7:19:55pm | info | Server listening on port 3030`

i've also noticed that glogg isn't automatically updating when new lines are added to the log and if i hit the refresh button, it's not loading in the new data in the log file i'm viewing.

**Comment by tmtron** [comment]
@selfagency could you post your winston file-format here? The original link is broken.
