### ISSUE TITLE
File follow feature not working on macOS

### ISSUE THREAD

**Issue by bcalmac** [nickbnf/glogg#174]
Enabling file follow with 'F' has no effect, I still need to reload the file to see updates. See the linked screencast that demonstrates trying to follow system.log:

https://youtu.be/my41-6gagBg

macOS: 10.12.6
glogg: 1.1.4

**Comment by bcalmac** [comment]
I have done some extra testing and noticed the following:
- glogg detects when a file is open for append and reloads it
- while the file is open and lines are added, glogg is silent, you need to refresh manually to get the most recent line.

I've written a Bash function for testing. The function writes 5 lines with a sleep of 1 sec between them. Then I call this function in a loop. Glogg does not detect the individual lines but refreshes every time the file is reopened.

    function write-lines {
        for i in {1..5}
        do
            echo "$(date) line $i"
            sleep 1
        done
    }

Then invoke it with:

    for i in {1..10}; do write-lines >> tmp.log; done

**Comment by rnyberg** [comment]
Got the same problem. Also options/advanced menu is missing so I cannot check the polling options. The menu is visible on Windows, but not on OSX.

**Comment by rnyberg** [comment]
@nickbnf - is this even supposed to work on macOS? 2 months+ radio silence is weird.

**Comment by variar** [comment]
On macOS glogg is using file watch provided by Qt. I've integrated [ Entropia File System Watcher](https://bitbucket.org/SpartanJ/efsw) in [klogg](http://github.com/variar/klogg) fork (9c60b3cd3017d940e90cae5632abdf16515e7d7d). Unfortunately, I don't have any computer with  macOS to test it. @rnyberg, @bcalmac  could you grab a build from CI and see if it works?
Binary --  https://s3.amazonaws.com/klogg.travis.build/variar/klogg/145/145.2/build/output/klogg
DMG (experimental) -- https://s3.amazonaws.com/klogg.travis.build/variar/klogg/145/145.2/build/packages/klogg-1.1.3-r145-OSX.dmg 

@nickbnf efsw library is cross-platform and is easy to build (it uses cmake but can be converted to qmake). In theory it can be used as common file watching backend for all platforms.

**Comment by nickbnf** [comment]
Good idea @variar re. efsw. File monitoring has never worked reliably apart from on Linux (using inotify), I've tried a number of options but to no avail. I'll try with klogg on the Mac.

**Comment by nickbnf** [comment]
I tried on macOS 10.12 with @bcalmac's test script and I see same behaviour with efsw (klogg) and Qt (glogg 1.1.4). The file is detected when closed/reopened by the shell but not in between the lines.

**Comment by variar** [comment]
esfw has two backends on mac: FSEvents and kqueue. It uses FSEvents by default. As far as I understand kqueue is more like inotify. I'll try to reconfigure the library to use kqueue.

**Comment by variar** [comment]
Build with kqueue backend:

- binary https://s3.amazonaws.com/klogg.travis.build/variar/klogg/151/151.2/build/output/klogg
- dmg https://s3.amazonaws.com/klogg.travis.build/variar/klogg/151/151.2/build/packages/klogg-1.1.3-r151-OSX.dmg

Please, try it out

**Comment by variar** [comment]
I quick idea about @bcalmac bash test. Could it be that `echo` calls  in `write-lines` function do not actually flush data to the file on disk? File must be flushed at the end of function and that might be the reason why glogg sees changes only after each iteration completes.

**Comment by bcalmac** [comment]
Flushing to disk is up to the OS. It shouldn't be necessary. Try following the file with tail, it works just fine.

**Comment by bcalmac** [comment]
I've tried the klogg dmg but it can't start because of a reference QT reference:

```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/bin/klogg.app/Contents/MacOS/klogg
  Reason: image not found
```

**Comment by variar** [comment]
I've managed to get my hands on mac os setup. This allowed to rework bundle packaging. Please try this one: https://s3.amazonaws.com/klogg.travis.build/variar/klogg/dev/klogg-dev-kqueue.dmg

I can confirm that version with FSEvents backend does not refresh file on each `echo`, but version with kqueue seems to work as expected.

I've also managed to set up glogg_itests  to run on CI. With efsw they passed on ubuntu  and mac, but failed  on windows. However, it looks more like tests and appveyor specific issue, as file opened in klogg is refreshing if I echo something to it manually. I'll look into it further.

**Comment by sogko** [comment]
@variar 
Jumping in here and the last klogg+kqueue build you share seems to be working for me (macOS 10.12.6)

**Comment by bcalmac** [comment]
@variar 

Sorry, I was away. Yes, I can confirm that it works for me too. I'm on High Sierra, 10.13.2. 

Thank you!

**Comment by itaybia** [comment]
@varier
the klogg_kqueue build works for me as well, but has another bug, where if i tell it to Follow the file, and also Auto-refresh the filter, the Follow is disabled.
any chance to get both working together?

**Comment by M00N-MAN** [comment]
on Mac OS Sierra & Mac OS Catalina a latest glogg version 1.1.4 still has no auto-refresh:
lets assume `bin.x` is a simple tcp/udp server listening some port and uses `printf()` to stdout for output and it has first line in `main(){ setbuf(stdout, NULL); //...`. An idea to use a server is better because it delivers some output only with some unpredictable outside activity of clients. as client i use list of telnets.

execute following:
`stdbuf -i0 -o0 -e0 ./bin.x > bin.log & tail -f bin.log`
or
`stdbuf -i0 -o0 -e0 ./bin.x | sed -n 'w bin.log' & tail -f bin.log`
shows each line

but with PATH='/Applications/glogg.app/Contents/MacOS/:$PATH'

`stdbuf -i0 -o0 -e0 ./bin.x > bin.log & glogg bin.log`
or
`stdbuf -i0 -o0 -e0 ./bin.x | sed -n 'w bin.log' & glogg bin.log`
shows only first two lines even if I press F key and/or check auto-refresh checkbox on UI.

only Reload button of UI works :|

ps:I didn't check same scenario on other platforms...

**Comment by variar** [comment]
@andrey-zibrov could you try latest [klogg](https://github.com/variar/klogg) release? 

Also glogg built from master branch may work.

p.s. Code for monitoring file changes uses native api for each platform, so results may be different
