### ISSUE TITLE
Load last session issues

### ISSUE THREAD

**Issue by Svish** [nickbnf/glogg#175]
Trying this out and quite like it, but there are a few annoyances with the **Load last session** option:

* If a log is set to follow, it should follow when loading last session too. Now I have to "re-f" each tab when I open the program.
* When glogg is associated with `.log` files and I double-click a file ...
  * while the program is running maximized, the window ends up restored, i.e. no longer maximized.
  * while the program is *not* running, the stored session is *thrown away* and *replaced* with the single clicked file, instead of *loaded* and *added* to!

Hoping these small issues can be fixed? 🤔

**Comment by variar** [comment]
Hi, @Svish. Which version of glogg on which OS are you using?
Replacing last session with new file if no other options are passed to first instance of glogg is indeed default behavior.  There is command line switch `--load-session` that can be added to command used to open `.log` files to force load last stored session.

Feature request to remember follow mode is better tracked in #183

**Comment by Svish** [comment]
Latest Windows 10, and latest glogg as of originally posted.

**Comment by variar** [comment]
You can modify registry key `HKEY_CLASSES_ROOT\Applications\glogg.exe\shell\open\command`. Adding `--load-session` to glogg command line should make it restore last session when open files by double click

**Comment by nickbnf** [comment]
Intended behaviour, as @variar pointed out, `--load-session` will do what you want.
