### ISSUE TITLE
Last search result is not fully visible when horizontal scrolling is active

### ISSUE THREAD

**Issue by WtfJoke** [nickbnf/glogg#208]
First of thank you for your tool. It saves me a ton of time and its performance is awesome! 🥇 

I have a small issue. I use glogg in version 1.1.0-1build3. 

If you have an unformatted(or minified) xml and you search something. The last search result is not fully displayed. And you cant scroll further.

See this image for clarification (its not possible to see line 208 fully):
![Issue](http://i.imgur.com/0N2EgBd.png)

You can test it with this [XML-file](https://gist.github.com/WtfJoke/fbca32ff77c9c14a3bd2500d1e1e3aa0/raw/ea09b3e27787376d7889ff69a1a819cff6e0910c/sample.xml) when searching for "SAX"

**Comment by variar** [comment]
This commit 9f0249b2be00dd32588facb5585bc2d3bf6626e5 should fix this issue.

**Comment by WtfJoke** [comment]
Cool :) I will try the latest version and test it. 

Thank you.
