### ISSUE TITLE
Wont open files with Russian characters in the file name.

### ISSUE THREAD

**Issue by chadbennett** [nickbnf/glogg#210]
If there is a Russian character in the file name Glogg will not open the file.

**Comment by variar** [comment]
What version are you using? I believe this issue was fixed by 661d48b073160cbad0cd23cdce0d98433f2509e0. It should be in version 1.1.1 and above. 

Also my fork (klogg) should not have this issue )

**Comment by nickbnf** [comment]
Closed as not reproducible on the latest version.
