### ISSUE TITLE
Glogg view isn't clear Windows 10

### ISSUE THREAD

**Issue by blabtonic** [nickbnf/glogg#213]
I've noticed that when I use glogg for a certain log file it opens up with text like this 
![capture](https://user-images.githubusercontent.com/6305320/39429353-a3e0fab0-4c58-11e8-957f-dad129505363.PNG)

I open a new log file and the log file opens fine both log files have pretty much the same type of information and are configured the same way

**Comment by fogoat** [comment]
I can't replicate this issue. Did you change text size in Windows to something other than 100%? glogg working great for me on Windows 10 64-bit Home & Pro.

**Comment by d-konrad** [comment]
I am having the same problem. I have two monitors. The larger monitor is scaled 150%, while the smaller one is scaled 100%. When glogg is opened on the large monitor and is moved to the small monitor, the text is fine. But if it is closed and then opened again on the small monitor, I get the same symptom.
