### ISSUE TITLE
Feature request : Lines wrapping

### ISSUE THREAD

**Issue by omasseau** [nickbnf/glogg#233]
It would be really nice to have an option for lines wrapping.
It is a bit annoying to have to scroll horizontally when a line is too long to fit the window ;)

**Comment by negora** [comment]
I think that it's a duplicate of #206 . But I agree, this feature would make a BIG difference. It's the only feature that I'm missing right now.

**Comment by nickbnf** [comment]
Closed as duplicate of #206
