### ISSUE TITLE
Lookbehind regex support

### ISSUE THREAD

**Issue by jgscherber** [nickbnf/glogg#248]
When trying to use lookbehind searches (`(?<=)` and `(?<!)`),  glogg give an error that
![image](https://user-images.githubusercontent.com/6207661/49307858-79330200-f4a4-11e8-977d-b601dc1b5cdc.png)
and looking at that bug ([QTBUG-2371](https://bugreports.qt.io/browse/QTBUG-2371)) support should have been added with QRegularExpression which has already been added to glogg (#159) so why is this error still showing?

Thanks

**Comment by variar** [comment]
Looks like there were no release with #159 integrated. Should be resolved with #243 when new build is released.

**Comment by variar** [comment]
@jgscherber could you check latest master build from CI
https://ci.appveyor.com/project/nickbnf/glogg/builds/21795819/artifacts?

Installer is buggy, but zip-archive should work fine.

**Comment by jgscherber** [comment]
The artifacts from the latest glogg build don't exist at that link anymore. I tested the latest version of klogg and there's no warning there so I'm closing this issue.
