### ISSUE TITLE
klogg opened a text file, >>3GB and >300k lines and gb2312 encoding.

### ISSUE THREAD

**Issue by variar** [nickbnf/glogg#252]
klogg opened a text file, >>3GB and >300k lines and gb2312 encoding.
all Chinese characters are garbled texts until the whole indexing of file finished completely.

_Originally posted by @NewUserHa in https://github.com/nickbnf/glogg/issues/243#issuecomment-462142001_

**Comment by variar** [comment]
Meant to create issue in other repository

**Comment by NewUserHa** [comment]
maybe glogg has this issue also?
my files were deleted so can not help ensure this for now.
this issue may should be opened?

**Comment by variar** [comment]
It might have the issue, but I don't remember details to state this without testing
