### ISSUE TITLE
New non-typing keybind to follow file

### ISSUE THREAD

**Issue by evandrocoan** [nickbnf/glogg#259]
Using only `f` is bad because most times I am typing things on the search box:
![image](https://user-images.githubusercontent.com/5332158/54554118-7516eb80-4992-11e9-9248-6f061ff4cf7c.png)

And if I want to follow the file back, most times end up typing `f` on the search box, other than using the follow action.

Can I use some other non-typing key to follow as F5?

**Comment by variar** [comment]
F5 is already used for reloading file. Implemented F10 in klogg builds >=19.07.0.428

**Comment by evandrocoan** [comment]
Thanks!!!!!!!!!!!!!
