### ISSUE TITLE
Windows Unicode full of spaces

### ISSUE THREAD

**Issue by thirdwheel** [nickbnf/glogg#270]
Hi

I've noticed that log files that are written in unicode are full of spaces (typically null bytes for non-Unicode characters) and it makes reading the logs a bit of a challenge.  It detects the encoding correctly (ISO-8859-1) but it doesn't remove the null bytes from the output.  A screenshot of the issue is below.

![image](https://user-images.githubusercontent.com/160601/65645868-765d5b00-e03c-11e9-81b6-52088ff85978.png)

**Comment by variar** [comment]
What version are you using? Sometimes encoding detection doesn't work. What happens if utf16 encoding is selected manually from the menu?

And could you attach a file sample? I'll try to check encoding detection for this file in both glogg and klogg.

**Comment by thirdwheel** [comment]
Sorry, version 1.1.4. UTF16 isn't listed as an option.  Log attached.
[ReportServerService__09_26_2019_00_06_50.txt](https://github.com/nickbnf/glogg/files/3660432/ReportServerService__09_26_2019_00_06_50.txt)

**Comment by variar** [comment]
Looks like utf16 didn't make it to version 1.1.4. You can try builds from latest master sources from https://github.com/nickbnf/glogg/issues/243#issuecomment-534721749 or switch to klogg (https://github.com/variar/klogg) which is more actively developed and supported.

**Comment by thirdwheel** [comment]
That's got it, thanks!
