### ISSUE TITLE
Hide not filtered lines

### ISSUE THREAD

**Issue by jjp91** [nickbnf/glogg#287]
In log file that is a merge of logs of all threads of an app, it would be usefull to see only the lines that are filtered.

A check box in the filter dialog would be nice.

Thanks.

**Comment by variar** [comment]
Hi, could you provide some more details/screenshots for this feature? Currently main view which shows all lines can be hidden by dragging the splitter up. This is a demo from [klogg](https://github.com/variar/klogg):

https://user-images.githubusercontent.com/1620716/119251962-ffca8500-bbb1-11eb-9681-e5525704a474.mp4

**Comment by jjp91** [comment]
Hi, your're right, I discovered that putting a '|' between two search strings can find both occurrences of lines and do as I would ask.

That is fine, don't need more. It's perfect.

Thanks for the tip.
