### ISSUE TITLE
Crash at 93% loading 1.4GB text file

### ISSUE THREAD

**Issue by stevekmcc** [nickbnf/glogg#43]
The file in question (267MB compressed) is here:
http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-m.gz

Windows 8, 32-bit, fresh glogg 0.9.1 install

Indexing lines... (93 %)
Microsoft Visual C++ Runtime Library
Runtime Error!
Program: C:\Program Files\glogg\glogg.exe

This application has requested the Runtime to terminate it in an
unusual way.
Please contact the application's support team for more information.

**Comment by nickbnf** [comment]
This should have been fixed a while ago.
