### ISSUE TITLE
glogg.pro:167: Unescaped backslashes are deprecated.

### ISSUE THREAD

**Issue by dwrobel** [nickbnf/glogg#54]
Just noticed this while compiling the 1.0.0 version from the official tarball:

WARNING: /home/dw/projects/fedpkg/glogg/master/glogg-1.0.0/glogg.pro:167: Unescaped backslashes are deprecated.

Please consider to apply the following patch:

--- glogg.pro.orig      2014-02-13 23:30:01.318911090 +0100
+++ glogg.pro   2014-02-13 23:30:06.982985581 +0100
@@ -164,7 +164,7 @@
 QMAKE_CXXFLAGS = -g
 
 # Which compiler are we using
-system( $${QMAKE_CXX} --version | grep -e " 4\\.[7-9]" ) {
+system( $${QMAKE_CXX} --version | grep -e " 4\\\\.[7-9]" ) {
     message ( "g++ version 4.7 or newer, supports C++11" )
     CONFIG += C++11
 }

BTW: There is one absolutely minor warning during compilation process:

src/sessioninfo.cpp:68:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for ( int i = 0; i < openFiles_.size(); ++i ) {

P.S.: Is the 1.0.0 version official? I didn't notice any information on the official web page, just got a notification from upstream monitoring[1]

[1]. https://bugzilla.redhat.com/show_bug.cgi?id=1064739

**Comment by dwrobel** [comment]
Can be closed.

**Comment by nickbnf** [comment]
Just to let you know. As of 1.0.2, both the Windows exe and the Debian package still use Qt4, though I have been using Qt5 for dev. Next version will probably be Qt5 only as we will use the new, much better Qt5 regex library.
