### ISSUE TITLE
Make quickfind interruptible

### ISSUE THREAD

**Issue by nickbnf** [nickbnf/glogg#60]
... by adding a letter or pressing 'Backspace'.
At the moment, quickfind uses the GUI thread, it should be moved to another thread.

**Comment by rvansa** [comment]
+1, this is the reason I'll probably won't use glogg

**Comment by rvansa** [comment]
And another thing - it would be useful if the search went forward and backward from the current position, so that I don't have to wait until whole log gets indexed when I need only the closest records.

**Comment by tanguero** [comment]
I disabled regex and the other fancy search in that box, so that it doesn't do that. Use a basic search and it works.
