### ISSUE TITLE
Reloading a file uses twice the memory (and can crash)

### ISSUE THREAD

**Issue by nickbnf** [nickbnf/glogg#85]

**Comment by hybridview** [comment]
This might be related to my issue as well. When I have a large log file open, if I hit refresh, then hit refresh again before the original refresh completes, glogg almost always crashes. Sometimes, I think glogg is trying to auto-refresh right before I manually hit refresh, causing the issue when I just refresh once.

Background:
When waiting for a response to show up in logs (using any viewer), I have a bad habit of hitting refresh too often to try and see it quicker. This always bites me when using glogg. :)

**Comment by nickbnf** [comment]
This has been fixed a while ago.
