### ISSUE TITLE
Is Glogg ever going to support Windows Unicode text files?

### ISSUE THREAD

**Issue by tanguero** [nickbnf/glogg#96]
Currently I have to convert them to look at them :(

Thanks.

**Comment by ferenczy** [comment]
As you can see on [Glogg's Google Group](https://groups.google.com/forum/#!topic/glogg-devel/kvOadvwxKBY), answer is **yes**:

> This is a popular request indeed and will be implemented in version 1.1.

But some estimate when the version 1.1 could be released would be nice.

**Comment by nickbnf** [comment]
utf-16 now supported.
